[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[ terminal.shell ]
  program = "fish"  

[ selection ]
  save_to_clipboard = true
[ scrolling ]
  history = 20000
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" 
[env]
TERM = "xterm-256color"
[font]

normal.family = "Iosevka Nerd Font"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"

size = 12.0

[terminal]
